export const INPUT: number = 0;
export const TEXTAREA: number = 1;
export const SELECT: number = 2;
export const HIDDEN: number = 3;
export const LABEL = -1;
export const REQUEST_SAVE = 4;
export const REQUEST_EDIT = 5;
export const REQUEST_DELETE = 6;
export const PAGE_SIZE = 3;
export const PAYMENT_CHOICE = ["", "CHECK", "ESPECE", "CARTE"];
export const ICOTERM = ["", "CTP", "CIP", "DAP", "DDP"];
export const DEVISE = ["", "MAD", "EUR", "DLR", "YEN"];
export const HOME=7
export const CLIENT_MANAGER=8
 export  const VENDOR_MANAGER=9 
 export  const PURCHASE_MANAGER=10
